# Generated by Django 4.2.8 on 2024-05-20 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('title_origin', models.TextField()),
                ('release_date', models.TextField()),
                ('status', models.BooleanField()),
                ('overview', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('poster', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(through='movies.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('movie', models.ManyToManyField(to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('movie', models.ManyToManyField(to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profile', models.TextField(blank=True, null=True)),
                ('movie', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
