# Generated by Django 4.2.8 on 2024-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='movie',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='review',
            field=models.ManyToManyField(to='movies.review'),
        ),
    ]
